name: folderstructure_pattern
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

#--------------------PACKAGES--------------------#
dependencies:
  flutter:
    sdk: flutter


#--------------------UTILITY PACKAGES--------------------#
  http: 
  intl: ^0.19.0
  logger:
  url_launcher:
  flutter_native_splash: ^2.4.0






#--------------------ICONS--------------------#
  iconsax:
  cupertino_icons: ^1.0.8



#--------------------STATE MANAGEMENT--------------------#

  get:
  get_storage:



#--------------------PRODUCT SPECIFIC--------------------#



#--------------------PACKAGES END--------------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true


#--------------------Assets--------------------#
  assets:
    - assets/logos/
    - assets/icons/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  #--------------------Local Fonts--------------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 300
        - asset: assets/fonts/Poppins-BoldItalic.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
          weight: 800
        





